mediaserver: Add libcameraservice dependency for legacy camera
 * When TARGET_HAS_LEGACY_CAMERA_HAL1 is set, the mediaserver
    includes CameraService.h but exported headers are missing

 * Error upon build due to missing libcameraservice linkage:
    fatal error: 'android/hardware/BnCameraService.h' file not found

Change-Id: Ib6bb8a4e9ef18606c64e2dff13504d2eeaac13b1